import Link from "next/link";
import { ArrowLeft, BrainCircuit, CloudSun, ExternalLink, MapPin, Sparkles } from "lucide-react";
import packageJson from "@/package.json";
import { WeatherFactCard } from "@/components/about/WeatherFactCard";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "About Me", description: "Meet Saksham Varma and learn how Atmos turns live forecasts into a calmer weather experience." };

const featureGroups = [
  { title: "Live conditions", items: ["Current and feels-like temperature", "Current conditions", "Rain probability and expected rainfall", "Wind speed, direction, and gusts", "Humidity and UV", "Sunrise and sunset"] },
  { title: "Forecast", items: ["Hour-by-hour forecast", "Today plus seven additional days", "Location search", "Optional device location", "Weather-responsive visual scenes"] },
  { title: "Personal experience", items: ["Multilingual greeting", "Weather jokes and worldwide facts", "Personal weather preferences", "Weather memory"] },
  { title: "Weather Intelligence", items: ["Interactive atmospheric timeline", "Auckland microclimate comparison", "Weather DNA and Momentum", "Activity, comfort, rain, wind, and rhythm analysis"] },
];

const technologies = ["Next.js", "React", "TypeScript", "Tailwind CSS", "Motion", "Open-Meteo", "Capacitor", "Progressive Web App support", "Local browser storage", "SVG and lightweight Canvas visualisation"];

export default function AboutPage() {
  return <main className="about-page"><div className="about-sky" aria-hidden><span /><span /><i /></div><div className="about-shell">
    <header className="about-header"><Link href="/" className="about-back"><ArrowLeft aria-hidden /> Back to Weather</Link><div className="about-nav-actions"><Link href="/analysis" className="about-back"><BrainCircuit aria-hidden /> Weather Intelligence</Link><div className="about-mark" aria-hidden><CloudSun /></div></div></header>

    <section className="about-hero" aria-labelledby="about-title"><div className="about-eyebrow"><Sparkles aria-hidden /> ABOUT THE CREATOR</div><h1 id="about-title">About Me</h1><p className="about-intro">Hello, I’m Saksham Varma.</p><p>I’m an analyst and developer with a Business Analytics qualification from the University of Auckland and a Bachelor of Technology in Information Technology, majoring in Cloud Computing.</p><p>I designed and developed Atmos to make everyday weather information feel clearer, calmer, and more personal. The app combines live forecast data, interactive visualisation, and explainable weather analytics in an interface that responds to the conditions around you.</p></section>

    <div className="about-grid">
      <section className="about-section"><div className="about-eyebrow">MY EDUCATION</div><h2>Business, technology, and cloud</h2><p>I completed a Business Analytics qualification at the University of Auckland, building on a Bachelor of Technology in Information Technology with a major in Cloud Computing.</p><p>Together, those disciplines shaped how I approach products: understand the data, design a clear experience, and build the technical systems that make it dependable.</p></section>
      <section className="about-section"><div className="about-eyebrow">ANALYST AND DEVELOPER</div><h2>From insight to interface</h2><p>My work sits between analysis and development. I enjoy turning complex information into patterns, comparisons, and practical insights, then expressing them through focused digital experiences.</p><p>Atmos combines data interpretation, user-experience design, responsive development, and lightweight visual animation.</p></section>
      <section className="about-section"><div className="about-eyebrow">MY BACKGROUND</div><h2>How I approached Atmos</h2><p>My background in Business Analytics shaped the app’s analytical foundation, while Information Technology and Cloud Computing informed its architecture and delivery. I wanted to go beyond displaying weather values and make the forecast easier to understand at a glance.</p></section>
      <section className="about-section"><div className="about-eyebrow">THE IDEA</div><h2>Why I built Atmos</h2><p>Many weather apps provide useful information, but the most important details can become difficult to interpret when everything is presented at once. Atmos was designed to organise weather information into a calmer experience that helps users understand what conditions are doing, how they may change through the day, and which periods may be better suited to different activities.</p></section>
    </div>

    <section className="about-section about-wide"><div className="about-eyebrow">THE EXPERIENCE</div><h2>What the app offers</h2><div className="about-feature-groups">{featureGroups.map((group) => <div key={group.title}><h3>{group.title}</h3><ul className="feature-list">{group.items.map((item) => <li key={item}>{item}</li>)}</ul></div>)}</div></section>

    <div className="about-grid">
      <section className="about-section intelligence-about-card"><div className="about-eyebrow">EXPLAINABLE ANALYSIS</div><h2>Weather Intelligence</h2><p>Weather Intelligence uses the forecast information already available in the app and turns it into visual, explainable analysis. It does not create a separate weather forecast or claim to replace professional forecasting models.</p><p>It includes an interactive hour-by-hour timeline, sunrise and sunset visualisation, Weather DNA, Momentum, Atmosphere Balance, Temperature and Wind Journeys, Rain Structure, Activity Matrix, Personal Weather Fit, Weather Personality, Weather Rhythm, microclimate comparison, and Weather Memory.</p><Link className="about-primary-link" href="/analysis">Explore Weather Intelligence <BrainCircuit aria-hidden /></Link></section>
      <section className="about-section"><div className="about-eyebrow">TRANSPARENT RULES</div><h2>How the analysis works</h2><p>The analysis is generated using transparent, rule-based calculations applied to current, hourly, and daily weather data. For example, the app can identify warming and cooling periods, expected rain windows, wind-direction changes, comfortable outdoor periods, and differences between nearby Auckland locations.</p><p>Scores such as Weather Fit, Sky Quality, activity suitability, and Weather Rhythm are app-generated convenience indicators. They are designed to explain the forecast and are not official scientific or safety ratings.</p></section>
      <section className="about-section"><div className="about-eyebrow">LIVE INFORMATION</div><h2>Weather data</h2><p>Forecast information is provided through Open-Meteo. Atmos requests data for the selected coordinates and presents it through the app’s visual and analytical interface. Weather is refreshed periodically rather than continuously every second.</p><a className="external-link" href="https://open-meteo.com/" target="_blank" rel="noopener noreferrer">Visit Open-Meteo <ExternalLink aria-hidden /></a></section>
      <section className="about-section"><div className="about-eyebrow">YOUR CHOICE</div><h2>Location and privacy</h2><p>Location access is optional. Atmos can use Auckland as its default location, allow you to search for another place, or use your device location when you grant permission.</p><p>The app may store the last successful location, cached weather, weather preferences, greeting state, saved weather memories, and recently displayed jokes or facts on your device. A selected city is saved only after its weather has loaded successfully. Atmos does not currently require an account.</p></section>
      <section className="about-section"><div className="about-eyebrow">RESILIENT BY DESIGN</div><h2>Reliability</h2><p>Atmos keeps the last successfully loaded forecast available when possible. If a city request fails, the app keeps the previous working location instead of replacing it with an empty screen. Cached information is clearly identified when fresh weather cannot be retrieved.</p></section>
      <section className="about-section"><div className="about-eyebrow">INCLUSIVE INTERACTION</div><h2>Designed for smooth performance</h2><p>The interface uses lightweight gradients, SVG graphics, controlled motion, and selective Canvas effects rather than large weather videos or heavy 3D scenes. Optional effects are reduced when the device or user preference calls for lower motion.</p><p>The app supports keyboard navigation, visible focus states, readable contrast, large touch targets, reduced-motion preferences, and text summaries for important weather insights.</p></section>
    </div>

    <section className="about-section about-wide"><div className="about-eyebrow">TECHNICAL DESIGN</div><h2>Built with</h2><div className="technology-list">{technologies.map((technology) => <span key={technology}>{technology}</span>)}</div></section>

    <section className="about-section about-wide limitations-section"><div><div className="about-eyebrow">IMPORTANT CONTEXT</div><h2>Important limitations</h2></div><div><p>Weather forecasts are estimates and may change as new information becomes available. Local conditions can differ from the forecast, particularly across coastal areas, hills, and different parts of Auckland.</p><p>The app-generated activity, comfort, sky-quality, and weather-personality insights are designed for convenience and interpretation. They should not be used as official medical, aviation, marine, emergency, or severe-weather guidance.</p></div></section>

    <WeatherFactCard />

    <section className="about-section author-section"><div><div className="about-eyebrow">APP DETAILS</div><h2>Designed in Auckland</h2><p>A calm weather experience designed around useful information and thoughtful interaction.</p></div><dl><div><dt>Created by</dt><dd>Saksham Varma</dd></div><div><dt>Role</dt><dd>Analyst and developer</dd></div><div><dt>Education</dt><dd>Business Analytics, University of Auckland · BTech Information Technology, major in Cloud Computing</dd></div><div><dt>Weather provider</dt><dd>Open-Meteo</dd></div><div><dt>Default location</dt><dd>Auckland, New Zealand</dd></div><div><dt>Version</dt><dd>{packageJson.version}</dd></div></dl></section>
    <section className="disclaimer"><MapPin aria-hidden /><div><h2>Official warnings</h2><p>For severe weather warnings, emergencies, marine conditions, and safety-critical decisions in New Zealand, always consult official local weather and emergency services.</p><a className="external-link" href="https://www.metservice.com/" target="_blank" rel="noopener noreferrer">Check official New Zealand weather warnings <ExternalLink aria-hidden /></a></div></section>
    <footer className="about-footer"><span>Atmos Weather</span><nav><Link href="/">Home</Link><Link href="/analysis">Explore Weather Intelligence</Link></nav></footer>
  </div></main>;
}
