export type WeatherFact = { id: string; fact: string; region: string };

export const weatherFacts: WeatherFact[] = [
  { id: "cloud-water", fact: "Clouds can contain enormous amounts of water even though individual droplets are extremely small.", region: "Worldwide" },
  { id: "antarctic-desert", fact: "Antarctica is the world’s largest desert because deserts are defined by low precipitation, not heat.", region: "Antarctica" },
  { id: "rain-smell", fact: "The earthy smell after rain is called petrichor and comes from compounds released by soil and plants.", region: "Worldwide" },
  { id: "rainbow-angle", fact: "A rainbow forms when sunlight is refracted, reflected, and dispersed inside water droplets.", region: "Worldwide" },
  { id: "lightning-heat", fact: "The air around a lightning channel becomes extremely hot for a fraction of a second, making it expand into thunder.", region: "Worldwide" },
  { id: "snow-shapes", fact: "Snow crystals grow with six-sided symmetry because of the molecular structure of frozen water.", region: "Worldwide" },
  { id: "fog-cloud", fact: "Fog is a cloud that forms at or very close to the ground.", region: "Worldwide" },
  { id: "wind-names", fact: "Many regions have traditional names for recurring local winds shaped by nearby mountains, valleys, and seas.", region: "Worldwide" },
  { id: "desert-cold", fact: "Some deserts become very cold at night because dry air and clear skies let heat escape quickly.", region: "Worldwide" },
  { id: "new-zealand-change", fact: "New Zealand’s maritime location and varied terrain can produce rapid changes in local weather.", region: "New Zealand" },
  { id: "southern-spin", fact: "Large weather systems generally rotate clockwise around low pressure in the Southern Hemisphere.", region: "Southern Hemisphere" },
  { id: "northern-spin", fact: "Large weather systems generally rotate anticlockwise around low pressure in the Northern Hemisphere.", region: "Northern Hemisphere" },
  { id: "sea-breeze", fact: "Sea breezes often develop on sunny days because land warms faster than nearby water.", region: "Coastal regions" },
  { id: "mountain-rain", fact: "Mountains can force moist air upward, cooling it and increasing rain or snow on the windward side.", region: "Mountain regions" },
  { id: "rain-shadow", fact: "The sheltered side of a mountain range can be much drier, creating an area known as a rain shadow.", region: "Worldwide" },
  { id: "aurora-weather", fact: "Auroras occur high above ordinary weather, where charged solar particles interact with Earth’s atmosphere.", region: "Polar regions" },
  { id: "monsoon-shift", fact: "A monsoon is a seasonal shift in wind that can create distinct wet and dry periods.", region: "Asia and beyond" },
  { id: "lake-snow", fact: "Cold air crossing a relatively warm lake can collect moisture and produce narrow bands of heavy snow downwind.", region: "Great Lakes" },
  { id: "cloud-colours", fact: "Clouds look white when their droplets scatter many colours of sunlight together, and grey when less light reaches their base.", region: "Worldwide" },
  { id: "halo", fact: "Rings around the Sun or Moon can form when light passes through ice crystals in high, thin clouds.", region: "Worldwide" },
  { id: "virga", fact: "Virga is rain or snow that falls from a cloud but evaporates before reaching the ground.", region: "Dry regions" },
  { id: "katabatic", fact: "Katabatic winds flow downhill when cold, dense air moves from high ground toward lower elevations.", region: "Polar and mountain regions" },
  { id: "trade-winds", fact: "Trade winds are dependable tropical winds that helped shape historic sailing routes across the oceans.", region: "Tropics" },
  { id: "cloud-height", fact: "Cirrus clouds form high in the troposphere and are made mostly of ice crystals.", region: "Worldwide" },
  { id: "dew", fact: "Dew forms when a surface cools enough for water vapour in nearby air to condense on it.", region: "Worldwide" },
  { id: "frost", fact: "Frost can form when surfaces cool below freezing and water vapour changes directly into ice.", region: "Cold regions" },
  { id: "equator-days", fact: "Day length changes relatively little through the year near the equator, helping keep seasonal temperatures more consistent.", region: "Equatorial regions" },
  { id: "ocean-moderation", fact: "Oceans warm and cool slowly, so coastal places often have smaller temperature swings than inland areas.", region: "Coastal regions" },
  { id: "pressure-wind", fact: "Wind begins when air moves from areas of higher pressure toward areas of lower pressure.", region: "Worldwide" },
  { id: "sunset-dust", fact: "Sunsets can appear red or orange because sunlight travels through more atmosphere and shorter blue wavelengths scatter away.", region: "Worldwide" },
];
